import { SignOutButton, SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Dashboard from "./dashboard";
import { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const router = useRouter();
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  useEffect(() => {
    if(isSignedIn) router.push("/dashboard");
  }, [isSignedIn])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {isSignedIn ? <SignOutButton /> : <SignInButton />}  
      </main>
    </>
  );
}

export default Home;
