import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import type { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect } from "react";
import LoadingSpinner from "~/components/LoadingSpinner";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const router = useRouter();
  const { user, isLoaded } = useUser();
  const login = api.user.login.useMutation();

  useEffect(() => {
    if (!isLoaded) router.push("/landing");
    if (isLoaded && user) {
      const { username, firstName, imageUrl } = user;

      login
        .mutateAsync({
          username: username ?? firstName ?? "",
          img_url: imageUrl,
        })
        .then(() => router.push("/dashboard"))
        .catch((error) => {
          console.error("Error occurred during login:", error);
        });
    }
  }, [isLoaded, user]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="apple flex min-h-screen flex-col items-center justify-center">
        {!isLoaded && <LoadingSpinner />}
      </main>
    </>
  );
};

export default Home;
